language: erlang
otp_release:
  - 22.0
  - 23.0
compiler: g++
os:
  - linux
  #- osx       # MacOS builds are not available on Travis

#  addons:
#    apt:
#      sources:
#        - ubuntu-toolchain-r-test
#      packages:
#        - g++-9
#  env: COMPILER=g++-9

before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq

install:
- sudo apt-get install -qq g++-9
- export CXX="g++-9"
